### PR TITLE
Migration to staging branch

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by scanon** [comment]
Is this running in CI already?

**Comment by rsutormin** [comment]
@scanon: no, it worked in CI on July 14th. After that moment there were some features added that are not necessary for current Appdev. Do you want them in Staging too?

**Comment by msneddon** [comment]
I think these changes are safe for staging.

**Comment by msneddon** [comment]
And I just made sure these changes were all already in develop:
https://github.com/kbase/narrative_method_store/compare/develop...rsutormin:dev-export-functions

**Pull request merged**
