### PR TITLE
Merge develop -> master for release

### PR DESCRIPTION
**Pull request by briehl**
* add support for dynamic dropdown fields
* add resource estimator spec definition to modules

### CODE REVIEW

**Comment by MrCreosote** [comment]
Needs release notes for the resource estimator stuff. @bio-boris?

**Comment by kkellerlbl** [comment]
Is it possible to bump the version?

**Comment by briehl** [comment]
Release notes in this PR: #76

**Comment by briehl** [comment]
Got release notes, got version bumped, anything else needed to merge?

**Comment by MrCreosote** [comment]
Not that I see

**Comment by MrCreosote** [comment]
Shane's review I guess

**Pull request merged**
