### PR TITLE
Bringing 'auth-service-url-allow-insecure' configuration parameter.

### PR DESCRIPTION
**Pull request by rsutormin**

### CODE REVIEW

**Comment by msneddon** [comment]
Shouldn't we make this parameter available for setting via test configs as well?  So updates to build.xml and the cfg_to_runner.py to pass it through.

**Comment by rsutormin** [comment]
@msneddon: It's added in previous PR: https://github.com/kbase/narrative_method_store/pull/47/files#diff-2cccd7bf48b7a9cc113ff564acd802a8R306

**Comment by rsutormin** [comment]
@msneddon: Done

**Comment by msneddon** [comment]
looks good

**Pull request merged**
